// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-4eIDktUNQPhWvC_Qiwzcx43vp8tFjs',
    appId: '1:480214961207:web:22ef633802c29bbec2c3b2',
    messagingSenderId: '480214961207',
    projectId: 'bedaya-hospitals',
    authDomain: 'bedaya-hospitals.firebaseapp.com',
    storageBucket: 'bedaya-hospitals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodWekYW3-lqS-3FQ-oOjowFffhnQk78Y',
    appId: '1:480214961207:android:4e2c888e0300fd14c2c3b2',
    messagingSenderId: '480214961207',
    projectId: 'bedaya-hospitals',
    storageBucket: 'bedaya-hospitals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmcEHPyYeugK_D8yM2ymkO_wqm7FgyAA',
    appId: '1:480214961207:ios:dd703aa603c1136cc2c3b2',
    messagingSenderId: '480214961207',
    projectId: 'bedaya-hospitals',
    storageBucket: 'bedaya-hospitals.firebasestorage.app',
    iosBundleId: 'com.example.bedaya2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWmcEHPyYeugK_D8yM2ymkO_wqm7FgyAA',
    appId: '1:480214961207:ios:b94690fe97ee32aec2c3b2',
    messagingSenderId: '480214961207',
    projectId: 'bedaya-hospitals',
    storageBucket: 'bedaya-hospitals.firebasestorage.app',
    iosBundleId: 'com.',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-4eIDktUNQPhWvC_Qiwzcx43vp8tFjs',
    appId: '1:480214961207:web:0376b1b7721c68aac2c3b2',
    messagingSenderId: '480214961207',
    projectId: 'bedaya-hospitals',
    authDomain: 'bedaya-hospitals.firebaseapp.com',
    storageBucket: 'bedaya-hospitals.firebasestorage.app',
  );
}
